version: '3'
services:
  caddy:
    container_name: "caddy"
    image: caddy:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config

  db:
    container_name: "gems_mysql"
    image: mysql:5.7.25
    environment:
      MYSQL_ROOT_PASSWORD: toon-me-eens-een-sterk-wachtwoord
      MYSQL_DATABASE: mms
      MYSQL_USER: grafana
      MYSQL_PASSWORD: "grafana-d!t-is-3cht-tOp_veilig"
      #MYSQL_ROOT_HOST: 192.168.0.0/255.255.0.0
      #MYSQL_HOST: 193.190.127.143/255.255.255.0
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      #- db_data:/users/opieters/webserver/management_interface/docker/data
      #- /users/opieters/webserver/management_interface/docker/data:/docker-entrypoint-initdb.d

  mirra_web:
    container_name: "mirra_web"
    build: ./mirra_web/
    depends_on:
      - db

  mqtt_broker:
    container_name: "mqtt_broker"
    image: eclipse-mosquitto
    ports:
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mqqt_broker/mosquitto.conf:etc/mosquitto/mosquitto.conf

  mqtt_parser:
    container_name: "mqtt_parser"
    build: ./mqtt_parser/
    depends_on: 
      - db
      - mqtt_broker

volumes:
  db_data: {}

networks:
  default:
    name: proxy

