site_name: 'MIRRA Documentation'

repo_url: https://github.com/Olocool17/MIRRA
repo_name: Olocool17/MIRRA

nav:
  - Overview: 'index.md'
  # - Hardware:
  # - Firmware:
  #   - Commands Reference
  #   - Code Documentation
  # - Server:
  # - User Manual:
  #   - Setting up the server
  # - Developer Manual:

theme:
  name: 'material'
  features:
    - navigation.path
    - toc.follow
    - content.action.view

  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: light
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.svg
  favicon: assets/favicon.png
  icon:
    view: material/file-eye

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  generator: false

extra_css:
  - stylesheets/extra.css

plugins:
  []